name: Spell checking
on: [push, pull_request]

permissions:
  contents: read

jobs:
  spelling:
    name: Spell checking
    permissions:
      contents: read
      pull-requests: read
      actions: read
    runs-on: ubuntu-22.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit

    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
    - uses: check-spelling/check-spelling@d7cd2973c513e84354f9d6cf50a6417a628a78ce # v0.0.21
      with:
        post_comment: '0'
